import React, { useEffect } from 'react';
import styled from 'styled-components';
import { useAppDispatch, useAppSelector } from '../redux/app/hooks.ts';
import { setFavorites, setLanguage } from '../redux/userPreferencesSlice';
import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

const Layout = ({ children }) => {
  const dispatch = useAppDispatch();
  const results = useAppSelector(state => state.content.results);

  useEffect(() => {
    if (localStorage.favorites) {
      const storedFavorites = localStorage.getItem('favorites');
      const selectedLanguage = localStorage.getItem('language');

      dispatch(setFavorites(JSON.parse(storedFavorites)));
      dispatch(setLanguage(selectedLanguage));
    }
  }, [])

  return (
    <>
      <Main>
        <Head>
          <title>ManipulaMusic</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div>{children}</div>
        <Footer />
      </Main>
    </>
  );
};

export default Layout;

const Main = styled.main`
  width: 100%;
  overflow-x: hidden;
`;
