import React, { useEffect } from 'react';
import { useAppDispatch, useAppSelector } from '../redux/app/hooks.ts';
import { setFavorites } from '../redux/userPreferencesSlice';
import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

const Layout = ({ children }) => {
  const dispatch = useAppDispatch();
  const results = useAppSelector(state => state.content.results)

  useEffect(() => {
    if (localStorage.favorites) {
      const storedFavorites = localStorage.getItem('favorites');
      dispatch(setFavorites(JSON.parse(storedFavorites)))
    }
  }, [])

  return (
    <>
      <Head>
        <title>ManipulaMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div>{children}</div>
      <Footer />
    </>
  );
};

export default Layout;
